name: Test Linux
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test:
    name: GitHub / 16cpu
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Runner Info
        run: |
          echo "::group::CPU"
          lscpu
          echo "::endgroup::"
          echo "::group::Memory"
          free -h
          echo "::endgroup::"
          echo "::group::Disk"
          df -h
          echo "::endgroup::"
      - name: Checkout start
        run: echo "CHECKOUT_START=$(date +%s)" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Checkout end
        run: echo "Checkout took $(( $(date +%s) - CHECKOUT_START )) seconds"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build start
        run: echo "BUILD_START=$(date +%s)" >> "$GITHUB_ENV"
      - name: Build
        run: make build-ci -j$(nproc) V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Build end
        run: echo "Build took $(( $(date +%s) - BUILD_START )) seconds"
      - name: Test start
        run: echo "TEST_START=$(date +%s)" >> "$GITHUB_ENV"
      - name: Test
        run: make run-ci -j$(nproc) V=1 TEST_CI_ARGS="-p actions --node-args='--test-reporter=spec' --node-args='--test-reporter-destination=stdout' --measure-flakiness 9"
      - name: Test end
        run: echo "Test took $(( $(date +%s) - TEST_START )) seconds"
